---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-conf-pvc
  namespace: elk
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# logstash规则文件（有不同的任务需要更改）
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-conf
  namespace: elk
data:
  # 基础镜像包含/etc/java/mysql-connector-java-8.0.17.jar
  # elasticsearch hosts 需要随着es服务更改
  logstash.conf: |
    input {
      jdbc {
        jdbc_connection_string => "jdbc:mysql://120.78.249.137:3306/db_pte"
        jdbc_user => "developer"
        jdbc_password => "developer123456"
        jdbc_driver_library => "/etc/java/mysql-connector-java-8.0.17.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        statement => "select id, id as idStr, type, code, title, stem, tags, createdAt, updatedAt from question where status = 1 and deletedAt is null and stem != '' and updatedAt > :sql_last_value"
        use_column_value => true
        tracking_column => "updatedAt"
        record_last_run => true
        last_run_metadata_path => "/.question_last_run"
        lowercase_column_names => false
        schedule => "* * * * *"
        }
      }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-api:9200"]
        index => "question"
        document_id => "%{id}"
        template_overwrite => true
      }
      stdout {
        codec => json_lines
      }
    }
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    elastic-app: logstash
  name: logstash
  namespace: elk
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      elastic-app: logstash
  template:
    metadata:
      labels:
        elastic-app: logstash
    spec:
      containers:
        - name: logstash
          image: justliu/btlogstash:6.8.2
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/
              name: config-volume
            - mountPath: /data
              name: logstash-data-volume
          ports:
            - containerPort: 5044
              name: filebeat
            - containerPort: 9600
              name: logstash
          env:
            - name: "XPACK_MONITORING_ELASTICSEARCH_URL"
              value: "http://elasticsearch-api:9200/"
          securityContext:
            privileged: true
      volumes:
        - name: config-volume
          configMap:
            name: logstash-conf
            items:
            - key: logstash.conf
              path: logstash.conf
        - name: logstash-data-volume
          persistentVolumeClaim:
            claimName: logstash-conf-pvc
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          
---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: logstash
  name: logstash-service
  namespace: elk
spec:
  ports:
    - port: 9600
      targetPort: 9600

